# Generated by Django 5.1.6 on 2025-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sunscreen', 'Sunscreen'), ('moisturizer', 'Moisturizer'), ('cleanser', 'Cleanser'), ('serum', 'Serum'), ('kits-combos', 'Kits and Combos'), ('facewash', 'Facewash')], default='moisturizer', max_length=50),
        ),
    ]
